POST https://localhost:7270/api/fruits HTTP/1.1
content-type: application/json

{
    "name": "apple"
}

###
POST https://localhost:7270/api/fruits HTTP/1.1
content-type: application/json
{
    "name": "orange"
}

###

GET https://localhost:7270/api/fruit

###

GET https://localhost:7270/api/fruits