POST https://localhost:7270/api/fruits HTTP/1.1
content-type: application/json

{
    "name": "apple"
}

###
GET https://localhost:7270/api/fruits
###
GET https://localhost:7270/api/fruits/apple
###
DELETE https://localhost:7270/api/fruits/apple
